from dataclasses import dataclass
from typing import Callable, Any, Set, List


@dataclass
class CyclicGroup:
    """
    A cyclic group is a finite group generated by one element.

    Let (G, *) be a finite group. The group G is cyclic if there exists
    an element g in G such that every element of G can be written as a
    power of g:

        G = <g> = {g^0, g^1, g^2, ..., g^(n-1)}

    where:
        g^0 = e
        g^1 = g
        g^2 = g * g
        g^3 = g * g * g
        ...

    The element g is called a generator of G.
    """

    elements: Set[Any]
    operation: Callable[[Any, Any], Any]
    identity: Any
    name: str = "Cyclic Group"
    operation_symbol: str = "*"

    def __post_init__(self):
        if self.identity not in self.elements:
            raise ValueError("The identity element must belong to the set of elements.")

    def operate(self, a: Any, b: Any) -> Any:
        """
        Compute a * b.
        """
        if a not in self.elements:
            raise ValueError(f"{a} is not an element of the group.")

        if b not in self.elements:
            raise ValueError(f"{b} is not an element of the group.")

        result = self.operation(a, b)

        if result not in self.elements:
            raise ValueError(f"The operation result {result} is not in the group.")

        return result

    def power(self, element: Any, exponent: int) -> Any:
        """
        Compute element^exponent using the group operation.

        In multiplicative notation:
            g^0 = e
            g^1 = g
            g^2 = g * g

        In additive groups, this corresponds to repeated addition.
        """
        if element not in self.elements:
            raise ValueError(f"{element} is not an element of the group.")

        if exponent < 0:
            raise ValueError("This educational version only supports non-negative exponents.")

        result = self.identity

        for _ in range(exponent):
            result = self.operation(result, element)

        return result

    def generated_sequence(self, generator: Any) -> List[Any]:
        """
        Return the sequence:

            g^0, g^1, g^2, ...

        until the sequence returns to an element already seen.
        """
        if generator not in self.elements:
            raise ValueError(f"{generator} is not an element of the group.")

        sequence = []
        seen = set()

        current = self.identity
        exponent = 0

        while current not in seen:
            sequence.append(current)
            seen.add(current)

            exponent += 1
            current = self.power(generator, exponent)

        return sequence

    def generated_set(self, generator: Any) -> Set[Any]:
        """
        Return the subgroup generated by one element:

            <g> = {g^0, g^1, g^2, ...}
        """
        return set(self.generated_sequence(generator))

    def element_order(self, element: Any) -> int:
        """
        Return the order of an element.

        The order of g is the smallest positive integer k such that:

            g^k = e
        """
        if element not in self.elements:
            raise ValueError(f"{element} is not an element of the group.")

        current = self.identity

        for k in range(1, len(self.elements) + 1):
            current = self.operation(current, element)

            if current == self.identity:
                return k

        raise ValueError(f"Could not determine the order of {element}.")

    def group_order(self) -> int:
        """
        Return the order of the group, that is, the number of elements in G.
        """
        return len(self.elements)

    def is_generator(self, element: Any) -> bool:
        """
        Check whether an element is a generator of the whole group.

        An element g is a generator if:

            <g> = G
        """
        return self.generated_set(element) == self.elements

    def generators(self) -> List[Any]:
        """
        Return all generators of the cyclic group.
        """
        result = []

        for element in self._sorted_elements():
            if self.is_generator(element):
                result.append(element)

        return result

    def is_cyclic(self) -> bool:
        """
        Check whether the group is cyclic.

        A group is cyclic if it has at least one generator.
        """
        return len(self.generators()) > 0

    def show_structure(self) -> None:
        """
        Display the basic structure of the group.
        """
        print(f"Group: {self.name}")
        print(f"G = {self._sorted_elements()}")
        print(f"Operation: {self.operation_symbol}")
        print(f"Identity element: {self.identity}")
        print(f"Order of the group: {self.group_order()}")

    def show_generators(self) -> None:
        """
        Display all generators of the group.
        """
        print(f"Generators: {self.generators()}")

    def show_powers(self, generator: Any) -> None:
        """
        Display the powers of a chosen generator.
        """
        if generator not in self.elements:
            raise ValueError(f"{generator} is not an element of the group.")

        print(f"Powers generated by {generator}:")

        sequence = self.generated_sequence(generator)

        for exponent, value in enumerate(sequence):
            print(f"{generator}^{exponent} = {value}")

    def show_verification(self) -> None:
        """
        Display whether the group is cyclic.
        """
        print("Verification:")
        print(f"Is cyclic: {self.is_cyclic()}")
        print(f"Generators: {self.generators()}")

    def _sorted_elements(self):
        """
        Return sorted elements when possible.
        """
        try:
            return sorted(self.elements)
        except TypeError:
            return list(self.elements)


# ------------------------------------------------------------
# Example: Z_5 under addition modulo 5
# ------------------------------------------------------------

def addition_mod_5(a: int, b: int) -> int:
    """
    Operation in Z_5:

        a * b = (a + b) mod 5

    Although the notation g^k is used in the code output,
    in an additive group it means repeated addition.
    """
    return (a + b) % 5


if __name__ == "__main__":
    Z5 = {0, 1, 2, 3, 4}

    cyclic_group_Z5 = CyclicGroup(
        elements=Z5,
        operation=addition_mod_5,
        identity=0,
        name="Z_5 under addition modulo 5",
        operation_symbol="+ mod 5"
    )

    cyclic_group_Z5.show_structure()
    print()

    cyclic_group_Z5.show_verification()
    print()

    generator = 1
    cyclic_group_Z5.show_powers(generator)
    print()

    print(f"Order of element {generator}: {cyclic_group_Z5.element_order(generator)}")